apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-node-selector
  name: test-node-selector
spec:
  containers:
  - image: redis
    name: redis
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    gpu: "false"
status: {}
