apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    env: demo
# Spec of replication controller
spec:
  template:
    metadata:
      labels:
        env: demo
      name: nginx
    # Spec of pod template
    spec:
      containers:
        - image: nginx
          name: nginx
  replicas: 5
  selector:
    matchLabels:
      env: demo
