apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-03-30T17:54:05Z"
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "101281"
  uid: 16f05f0c-4cff-4db9-8e1c-d6e8e89cb3de
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
  nodeName: cka-cluster1-control-plane